GET https://localhost:5004/catalog/categories/
  ?$select=CategoryId,CategoryName
###
GET https://localhost:5004/catalog/products/
  ?$filter=startswith(ProductName,'Ch') or (UnitPrice gt 50)
###
GET https://localhost:5004/catalog/products/
  ?$orderby=UnitPrice desc,ProductName
  &$select=ProductId,ProductName,UnitPrice
###
GET https://localhost:5004/catalog/categories/
  ?$select=CategoryId,CategoryName
  &$expand=Products
###
GET https://localhost:5004/catalog/products(50)
###
GET https://localhost:5004/v2/products(50)
###
GET https://localhost:5004/ordersystem/customers
  ?$filter=Country eq 'Germany'
###
GET https://localhost:5004/catalog/products(77)
###